<?php
/**
 * Created by PhpStorm.
 * User: ivoglent
 * Date: 6/15/18
 * Time: 12:13 AM
 */

namespace ivoglent\yii2\filemanager;


use yii\base\InvalidConfigException;
use yii\web\ServerErrorHttpException;

class Module extends \yii\base\Module
{
    public $defaultRoute = 'dialog/index';
    /**
     * Base of upload directory
     * @var string
     */
    public $baseUploadDirectory = '';

    /**
     * Base of user directory
     * default value is false mean all files will be stored in same folder
     * if  you want to use base directory for each user just config $userDir as username or user ID
     *
     * @var bool|string
     */
    public $userDir = false;

    /**
     * Path to published assets url
     * @var string
     */
    public $assetUrl = '';

    /**
     * Path to published assets path
     * @var string
     */
    public $assetPath = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->baseUploadDirectory)) {
            throw new InvalidConfigException('No baseUploadDirectory defined');
        }
        $this->publishAssets();
    }

    /**
     * Publish module's assets to @web/assets folder
     * Then store published url to Module property in order to use inside this module
     */
    public function publishAssets() {
        $assetDir = dirname(__FILE__) . '/assets';
        $result = \Yii::$app->assetManager->publish($assetDir);
        if (empty($result)) {
            throw new ServerErrorHttpException('Can not publish filemanager assets');
        }
        $this->assetPath = $result[0];
        $this->assetUrl = $result[1];
    }
}